name: DockerImageBuild

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USER }}
          password: ${{ secrets.HUB_PASS }}

      - name: Generate Version
        run: date +%Y%m%d%H%M%S > VERSION
        shell: bash

      - name: Read Version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.HUB_USER }}/${{ secrets.HUB_REPO }}:latest
            ${{ secrets.HUB_USER }}/${{ secrets.HUB_REPO }}:${{ env.VERSION }}
          platforms: linux/amd64, linux/arm64

